### PR TITLE
begin fixing issue no.1 by hit-1170300817

### PR DESCRIPTION
**Pull request by 1170300817**
i am working on the problem stated at issue #1

### CODE REVIEW

**Review by 1170500820 — COMMENTED** [review]
ok

**Comment by 1170300817** [comment]
> ok

i think i fixed the problem at #1 . can you check it?

**Comment by 1170500820** [comment]
Thanks a lot, this code could work now. Can you provide a better one?

**Comment by 1170300817** [comment]
i made a better solution in src\dynamic\simpleregex\BetterSolution.java. you can check it out.

**Comment by 1170500820** [comment]
you are a genius! I will merge it.

**Pull request merged**
